FROM node:12.10-alpine

WORKDIR /app

RUN apk update \
  && apk --no-cache add git ca-certificates wget

RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-2.30-r0.apk \
  && apk --no-cache add glibc-2.30-r0.apk

COPY package.json .
# COPY yarn.lock .
# RUN yarn install
# https://blog.odaryo.com/2020/01/nodejs-dockerfile-yarn-error/

COPY .flowconfig .
RUN yarn global add flow-typed \
  && flow-typed install

COPY . .

EXPOSE 3000

CMD yarn start