version: "3"

services:
  web:
    command: "yarn start --host 0.0.0.0 --port 3000"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app